### PR TITLE
Add namespaces to staging resources and preserve securityContext on stage pods

### PR DESCRIPTION
**Pull request by dymurray**
This PR does 2 things.
* Add the stage label to all target namespaces so that they are explicitly included in the stage backup/restore. This allows us to mutate the annotations from within the plugin.
* Include the application pod's `securityContext` field when creating the stage pod to ensure it runs as the same uid/gid.

### CODE REVIEW

**Comment by dymurray** [comment]
https://github.com/fusor/openshift-migration-plugin/pull/8

**Comment by dymurray** [comment]
I am seeing a log statement after the stage restore runs when deleting annotations on the stage resources:
```
{"level":"error","ts":1564518878.9188626,"logger":"migration|t89hk","msg":"","error":"pods \"mariadb-1-jc48w-stage\" is forbidden: unable to validate against any security context constraint: []","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:341\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:297\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:367\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

It's something I want to investigate but nothing is broken. The stage pod still ran successfully and restic successfully performs a podvolumerestore. I think it has to do with `deleteAnnotations` or the stage cleanup process.

**Comment by jmontleon** [comment]
ACK

**Comment by jwmatthews** [comment]
I tested this PR along with https://github.com/fusor/openshift-migration-plugin/pull/8
Migrated mediawiki
Used 2 NFS PVs (ensured that I had no_root_squash on nfs server)

Stage/Migration was successful.

Did see the odd error messages as dylan mentioned, but was successful.

Running into an issue of mediawiki not coming up but think that is related to mediawiki details and not migration process.

**Comment by Danil-Grigorev** [comment]
@dymurray The same error pops up, when the stage pod was strictly assigned to a specific SCC. I was seeing this message, after ensuring the pod deploys under the same SCC on source and target. This happened before the fix, so your guess is probably correct.

**Comment by dymurray** [comment]
Thanks @Danil-Grigorev, good to know that this was happening before the fix as well. Makes me less concerned but I will open an issue to track it.

**Comment by dymurray** [comment]
Opened an issue to track:
https://github.com/fusor/mig-controller/issues/228

**Comment by jortel** [comment]
> Opened an issue to track:
> #228

@dymurray can #228 be closed?

**Pull request merged**
